Repository LinkerApplication/cv-generator, pull requests merged in 2021-09, with the labels that each got.

#18 Creating a project
  .gitignore
  backend/generator/core/__init__.py
  backend/generator/core/settings.py
  backend/generator/core/urls.py
  backend/generator/core/wsgi.py
  backend/generator/manage.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: business logic

#20 Poetry problem solved
  backend/poetry.lock
  backend/pyproject.toml
Labels: infrastructure

#21 created app and model
  backend/generator/core/settings.py
  backend/generator/profile/__init__.py
  backend/generator/profile/admin.py
  backend/generator/profile/apps.py
  backend/generator/profile/migrations/0001_initial.py
  backend/generator/profile/migrations/__init__.py
  backend/generator/profile/models.py
Labels: business logic

#25 Basic dockerezation of the backend
  backend/Dockerfile.dev
  backend/generator/core/settings.py
  docker-compose.yml
Labels: infrastructure

#26 created model works place
  backend/generator/profile/migrations/0002_experience.py
  backend/generator/profile/models.py
Labels: business logic

#28 PG admin integration to the project
  docker-compose.yml
Labels: infrastructure

#29 Init pytest [WIP]
  backend/generator/profile/migrations/0001_initial.py
  backend/generator/profile/migrations/0002_experience.py
  backend/generator/profile/migrations/__init__.py
  backend/generator/profile/models.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/pytest.ini
Labels: tests
